/**
 * Feature flag configuration for Sketch2Mermaid.
 */

/**
 * When true, the shape palette uses static SVGs pre-generated by Mermaid.
 * When false, it falls back immediately to the legacy hand-drawn inline SVG paths.
 * Can be toggled without requiring any code rollbacks or git reverts.
 */
export const USE_MERMAID_GENERATED_SHAPE_ICONS = true;

/**
 * When true, enables the subgraphs and swim-lanes visual grouping system.
 */
export let USE_GROUPS_AND_SWIMLANES = true;
export function setUseGroupsAndSwimlanes(val: boolean) {
  USE_GROUPS_AND_SWIMLANES = val;
}

/**
 * When true, the canvas uses thin orthogonal edge routing and smaller arrowheads.
 * When false, it falls back immediately to the legacy curved Bézier paths and styling.
 */
export const USE_MERMAID_LIKE_EDGE_RENDERING = true;

/**
 * When true, imports compile with a layout configured to mimic Mermaid.js's
 * native vertical/horizontal rank alignments and spacing.
 */
export let USE_MERMAID_LIKE_IMPORTED_LAYOUT = true;
export function setUseMermaidLikeImportedLayout(val: boolean) {
  USE_MERMAID_LIKE_IMPORTED_LAYOUT = val;
}

/**
 * When true, browser Mermaid imports emit structured diagnostics to the console
 * and to window.__S2M_LAST_MERMAID_IMPORT_DIAGNOSTICS__.
 */
export const DEBUG_MERMAID_IMPORT_LAYOUT = false;

// ---------------------------------------------------------------------------
// Layout spacing constants for Mermaid-like diagrams
//
// Values mirror Mermaid's own Dagre integration (source of truth:
// packages/mermaid/src/rendering-util/layout-algorithms/dagre/index.js and
// packages/mermaid/src/diagrams/flowchart/flowRenderer-v3-unified.ts):
//   - nodeSpacing / rankSpacing default to 50 (flowchart config)
//   - graph margins are marginx: 8, marginy: 8
//   - Mermaid does NOT set `edgesep` or `acyclicer` (Dagre defaults apply)
// ---------------------------------------------------------------------------
export const MERMAID_LIKE_RANK_SEP = 50;
export const MERMAID_LIKE_NODE_SEP = 50;
export const MERMAID_LIKE_MARGIN_X = 8;
export const MERMAID_LIKE_MARGIN_Y = 8;
export const MERMAID_LIKE_LABEL_PADDING = 32;
export const MERMAID_LIKE_MIN_EDGE_BEND = 20;

/**
 * Extra rank separation applied inside recursively laid out subgraphs.
 * Mermaid: `node.graph.setGraph({ ranksep: ranksep + 25, nodesep })` in
 * measureDagreGraph (dagre/index.js).
 */
export const MERMAID_LIKE_SUBGRAPH_RANK_SEP_EXTRA = 25;

/**
 * Padding between a cluster's children bounding box and the cluster border.
 * Mermaid: flowDb.getData() sets `padding: 8` on subgraph nodes; the cluster
 * rect is drawn with that padding around the children bounds.
 */
export const MERMAID_LIKE_CLUSTER_PADDING = 8;

/**
 * Deterministic height reserved for the subgraph title band on the canvas.
 * Mermaid draws the cluster title inside the top of the cluster rect; our
 * GroupNode renders a title area (~13px font + 2×8px padding + border ≈ 32px).
 * This is a canvas-only visual constant, never exported to Mermaid.
 */
export const MERMAID_LIKE_GROUP_TITLE_HEIGHT = 32;

/**
 * Threshold (in pixels) below which nodes are considered to be on the same rank (sibling nodes).
 * If undefined/null, defaults dynamically to MERMAID_LIKE_RANK_SEP / 2.
 */
export const MERMAID_LIKE_SAME_RANK_THRESHOLD = MERMAID_LIKE_RANK_SEP / 2;

/**
 * When true, click-dragging on an empty area of the canvas draws a selection rectangle
 * to select multiple nodes. When false, click-dragging on the pane pans the viewport.
 */
export const USE_LASSO_SELECTION = true;

// ---------------------------------------------------------------------------
// Visual Groups and Swimlanes layout constants
// ---------------------------------------------------------------------------
export const DEFAULT_GROUP_WIDTH = 420;
export const DEFAULT_GROUP_HEIGHT = 260;
export const DEFAULT_LANE_WIDTH_LR = 900;
export const DEFAULT_LANE_HEIGHT_LR = 220;
export const DEFAULT_LANE_WIDTH_TD = 320;
export const DEFAULT_LANE_HEIGHT_TD = 700;
export const GROUP_PADDING = 40;
export const GROUP_MEMBERSHIP_TOLERANCE = 15;
export const MIN_GROUP_WIDTH = 240;
export const MIN_GROUP_HEIGHT = 140;

/** Snapping distance in pixels for edge endpoints */
export const SNAP_THRESHOLD = 25;

import { APP_VERSION as appVersion } from './appVersion';

/** Current application version */
export const APP_VERSION = appVersion;

/** Feature flag configuration for changelog notifications */
export const USE_CHANGELOG_NOTIFICATIONS = true;
export const CHANGELOG_NOTIFICATION_MIN_IMPORTANCE: 'minor' | 'normal' | 'major' = 'normal';





